### ISSUE TITLE
Code Availability for ConsistI2V Project?

### ISSUE THREAD

**Issue by Njasa2k** [TIGER-AI-Lab/ConsistI2V#1]
Hi there!

I'm excited about the ConsistI2V project's ability to have consistent image to video as the source. I noticed the code isn't currently available in the repository. While I understand it's still under development, I'm curious if there's any information about a potential release timeframe.

I appreciate any insights you can share about the code's availability. Thanks for your time and the awesome project!

**Comment by howardgriffin** [comment]
waiting for the code...

**Comment by wenhuchen** [comment]
We will release it very soon. Stay tuned.

**Comment by wren93** [comment]
Thank you for your interest. We have released our code in this repo and model at https://huggingface.co/TIGER-Lab/ConsistI2V.
