### ISSUE TITLE
watermark problem

### ISSUE THREAD

**Issue by Scofieldtangsiwei** [TIGER-AI-Lab/ConsistI2V#11]
Hi,

I wonder why there is always a watermark like pattern appealing in the generated video? Any idea how to get rid of it?

**Comment by wren93** [comment]
Hi, this is a problem with the Webvid-10M training dataset where all the videos in the dataset have a "shutterstock" watermark at the same position of the video. We use the center cropped videos in the dataset or their horizontal flips to train the model, therefore there will likely be a watermark at the middle part of the video. We are working on training the model on watermark-free datasets to get rid of this problem.
