### ISSUE TITLE
How can I fine-tune the provided model?

### ISSUE THREAD

**Issue by Henrik-hw** [TIGER-AI-Lab/ConsistI2V#12]

**Comment by wren93** [comment]
Hi, please checkout the [training script](https://github.com/TIGER-AI-Lab/ConsistI2V/blob/main/train.py) and the [training configuration](https://github.com/TIGER-AI-Lab/ConsistI2V/blob/main/configs/training/training.yaml). You can replace `pretrained_model_path` in the training configuration with `TIGER-Lab/ConsistI2V` to finetune from the pretrained model.
