### ISSUE TITLE
Question about negative prompt

### ISSUE THREAD

**Issue by yujiangpu20** [TIGER-AI-Lab/ConsistI2V#14]
Thank you for sharing the excellent work! I am confused about the "negative prompt" shown in your demo and code. It seems that you didn't mention that in your paper. What is it used for?

**Comment by wren93** [comment]
Hi, thanks for your interest. The negative prompt is used to represent what you don't want to see in the generated video. It is used in the unconditional branch of CFG. It generally applies to all diffusion models with CFG and is not limited to our model.  More Info: https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Negative-prompt
