### ISSUE TITLE
Checkpoint can't be downloaded

### ISSUE THREAD

**Issue by Yutong18** [TIGER-AI-Lab/ConsistI2V#16]
Dear Authors,
Thank you for your great work. Could you please help check that the checkpoint is not available now on the Huggingface. Thank you!

**Comment by wren93** [comment]
Hi, it seems that we are still able to download the checkpoint from huggingface. Maybe it's an issue related to connecting to huggingface on your side? You can try some mirror websites like https://hf-mirror.com/
