### ISSUE TITLE
Discussion on Computing Resources and Training Details

### ISSUE THREAD

**Issue by HUuxiaobin** [TIGER-AI-Lab/ConsistI2V#18]
Thank you for your significant contributions. I attempted to use consistI2V to train our tasks, and found that each iteration takes approximately 24.14s/it, based on the default parameters (8 GPUs with 3 batch size with 256x256 resolution). I'm curious about the duration of each iteration when you use the default training YAML. Could you share your experience?

**Comment by wren93** [comment]
Hi, what kind of gpu are you using? We were using 16 A800s and it takes about 6 seconds per iteration.
