### ISSUE TITLE
Support of Multi-GPU inference

### ISSUE THREAD

**Issue by yujiangpu20** [TIGER-AI-Lab/ConsistI2V#19]
Hi, I've tried some samples with good results, and I'm wondering if there is support for multi-GPU parallel inference?

**Comment by wren93** [comment]
Hi, it should be possible. You can use the accelerate library along with a dataloader. You will need to use accelerator.prepare(dataloader) to prepare the dataloader and move the model to accelerator.device to support multi gpu inference.
