### ISSUE TITLE
Hardware requirements

### ISSUE THREAD

**Issue by YongLD** [TIGER-AI-Lab/ConsistI2V#20]
Your work is very interesting！！ I have a few questions I'd like to ask.
How many 40GB A100 GPUs are needed if the batch size is 3 and the sample size is around 12?  What are the hardware requirements for your training? How long is the training time needed?

**Comment by wren93** [comment]
Hi, may I ask what does it mean by sample size around 12?

If using the default configuration (16 frames, 256x256, bf16), it takes more than 60G GPU memory to fit in a batch size of 3 for each GPU. We were using 16 80G A800s and it takes ~2 weeks to train the model.

**Comment by YongLD** [comment]
Thanks for your reply! Since I only have six 40GB A100 GPUs, I have changed sample_n_frames to 6 and batchsize to 2. I would like to ask if these configurations can be reduced if it is for fine-tuning with consisiti2v model. Which parameters can be adjusted to lower the GPU memory requirements?

**Comment by wren93** [comment]
I think it should be able to fit in 40 GB memory. Training with less frames and less batch sizes can lower the memory requirement. You can set `gradient_accumulation_steps` in the training config to simulate larger batch sizes.

**Comment by YongLD** [comment]
This solution is excellent! I completely forgot that gradient_accumulation_steps can be used to simulate a larger batch size. Thank you so much!
