### ISSUE TITLE
Question about Long Video Generation

### ISSUE THREAD

**Issue by Yanyirong** [TIGER-AI-Lab/ConsistI2V#21]
Thanks for your excellent job! This is very interesting!

Here is a question of the long video generation. In the section 5.5 of the article. You show that you have generated long video in chunks. I wonder if this function is supported in the released code now. If so, how can I use the scripts?
![image](https://github.com/user-attachments/assets/cdea7e23-0ede-413f-9656-679e1764b5c1)

**Comment by wren93** [comment]
Hi, please take a look at `scripts/animate_autoregress.py` and `configs/inference/inference_autoregress.yaml`
