### ISSUE TITLE
Finetuning model loading

### ISSUE THREAD

**Issue by YongLD** [TIGER-AI-Lab/ConsistI2V#22]
How should I load the model that I saved midway during fine-tuning? Such as `checkpoint-94000`. It doesn't seem correct when I load it into the `pretrained_model_path` parameter. Which parameter should it be loaded into? Is it `pipeline_pretrained_path`?

**Comment by YongLD** [comment]
Would it be sufficient if I override the `unet` parameters? During model fine-tuning, were only the `unet` parameters fine-tuned?

**Comment by wren93** [comment]
Hi, you are right that only the unet parameters are fine-tuned. We kept the text encoder and vae parameters frozen throughout the finetuning. The checkpoint files under `checkpoint-xxxx` only contain the unet weights.

For the saved checkpoints, you can first load the base model (e.g. sd 2) and the unet weights from the checkpoint in `scripts/animate.py` using `pretrained_model_path` and `unet_path`. You can then save the pipeline by setting the flag `--save_model` in `scripts/animate.py`, which will save the entire pipeline to the inference output directory. Later you only need to set the `pipeline_pretrained_path` to this directory to use the model.

**Comment by YongLD** [comment]
Thank you very much for your answer! I have another question. I want to change the base model to Stable Diffusion 3. What should I pay attention to, and can I directly replace it?
