### ISSUE TITLE
How to change fps

### ISSUE THREAD

**Issue by Vedant1599** [TIGER-AI-Lab/ConsistI2V#23]
First of all excellent work guys. I am playing around with your model the results are good but I want to improve change fps is there any for it?

**Comment by wren93** [comment]
Hi, please refer to `configs/inference/inference.yaml` -> sampling_kwargs -> frame_stride, you can change it to a different value to control the output motion magnitude. If you want to save the video with different fps, you can refer to this function `save_videos_grid` (https://github.com/TIGER-AI-Lab/ConsistI2V/blob/main/consisti2v/utils/util.py#L21) which has a `fps` parameter that controls the output fps of the video.
