### ISSUE TITLE
can something like this work with cogvideox I2V?

### ISSUE THREAD

**Issue by nunbuzor** [TIGER-AI-Lab/ConsistI2V#25]

**Comment by TruthSearcher** [comment]
@nunbuzor

**Comment by TruthSearcher** [comment]
@wenhuchen

**Comment by TruthSearcher** [comment]
@wenhuchen will this repo support cogvideox?

**Comment by wenhuchen** [comment]
I think cogvideox already supports I2V now.

**Comment by TruthSearcher** [comment]
> I think cogvideox already supports I2V now.

however cogvideox gets progressively worse in quality when trying to generate I2V using the last frame of the generated video. Is that something ConsistI2V is supposed to be better at?

**Comment by wren93** [comment]
This is quite common for I2V models if you want to generate longer videos autoregressively. As ConsistI2V is in general an older and weaker model I don't think it will generate better quality videos than cogvideox. However you can try to add the FrameInit part of ConsistI2V to cogvideox and see if it leads to better results
