### ISSUE TITLE
How to increase the resolution of the resulting video?

### ISSUE THREAD

**Issue by 0Godness** [TIGER-AI-Lab/ConsistI2V#4]
Thanks for your interesting work and the nice code!
I want to know how to increase the resolution of the resulting video, it need re-training using the dataset of bigger resolution?

**Comment by wren93** [comment]
Hi, thank you for your interest. The model should still be able to generate videos for some cases at a slightly higher resolution (e.g. 320x512), but it's true that it is trained on lower resolution data and may need retraining to better adapt to high res data. We are working on improving the quality of the generated videos at higher resolutions.

**Comment by SkylerZheng** [comment]
@wren93 For higher resolution experiments, have you seen frame jumping issue? Namely, the generated video is different from the conditioned image?
