### ISSUE TITLE
Where to download the Training Dataset 

### ISSUE THREAD

**Issue by csguoh** [TIGER-AI-Lab/ConsistI2V#5]
Hi authors,
Thanks for this awesome work! In the paper, the ConsistI2V is trained with WebVid-10M dataset. If I want to reproduce the training, which website should I refer to download this dataset?  Thanks

**Comment by wren93** [comment]
Hi, thanks for the interest. The dataset should be available [here](https://github.com/m-bain/webvid) but according to its recent update the URLs to the videos are no longer available. There might be some alternative solutions like [this](https://github.com/m-bain/webvid/issues/21) but I'm not sure if this is working.
