### ISSUE TITLE
The camera motion cannot be used

### ISSUE THREAD

**Issue by 0Godness** [TIGER-AI-Lab/ConsistI2V#7]
Hello, Thanks for your nice work! I want to use the code to achieve the camera motion result. By simply setting the camera motion (such as pan_left), the dim match would generate some problems in z_T calculation. So how to use the code correctly to get the camera motion results?

**Comment by wren93** [comment]
Hi, thanks for your interest. Can you provide more information about the error in `z_T` and your inference config?
