### ISSUE TITLE
Why does the video generated by the model I trained appear to collapse?

### ISSUE THREAD

**Issue by Henrik-hw** [TIGER-AI-Lab/ConsistI2V#9]
Data: WebVid10M( 80K video data were selected)
train epochs: 120,000

**Comment by wren93** [comment]
Hi, did you train from scratch or finetune from our checkpoint? We discovered that it's often not very stable to finetune from our pretrained model. We are still working on improving this baseline model. If it's training from scratch, I'm not sure if 80k videos is large enough.

**Comment by Henrik-hw** [comment]
> Hi, did you train from scratch or finetune from our checkpoint? We discovered that it's often not very stable to finetune from our pretrained model. We are still working on improving this baseline model. If it's training from scratch, I'm not sure if 80k videos is large enough.

Thanks for the advice. I started training from scratch. I will try to add more videos.
